services:
  opencode:
    image: ghcr.io/hung319/opencode-webui-docker:latest
    pull_policy: always
    container_name: opencode
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../files/opencode.json:/root/.config/opencode/opencode.json
      - ../files/auth.json:/root/.local/share/opencode/auth.json
